version: '2'
services:
    nginx-proxy:
        image: jwilder/nginx-proxy:latest
        container_name: nginx-proxy
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
        ports:
            - 80:80
        restart: always

    # plex:
    #     image: linuxserver/plex
    #     container_name: plex
    #     volumes:
    #         - /home/mike/nas_mount/config/plex:/config
    #         - /home/mike/nas_mount/TV:/data/tvshows
    #         - /home/mike/nas_mount/Movies:/data/movies
    #         - /home/mike/nas_mount/bond:/data/bond
    #     network_mode: host
    #     ports:
    #         - 32469:32469
    #         - 32400:32400
    #         - 32401:32401
    #         - 3005:3005
    #         - 8324:8324
    #         - 1900:1900/udp
    #         - 32410:32410/udp
    #         - 32412:32412/udp
    #         - 32413:32413/udp
    #         - 32414:32414/udp
    #     env_file: uidgid.env
    #     environment:
    #         - VIRTUAL_HOST=plex.logan.loc
    #         - VIRTUAL_PORT=32400
    #     restart: always

    sonarr:
        image: linuxserver/sonarr
        container_name: sonarr
        volumes:
            - /home/mike/nas_mount/config/sonarr:/config
            - /etc/localtime:/etc/localtime:ro
            - /home/mike/nas_mount/TV:/tv
            - /home/mike/nas_mount/Downloads/complete:/complete
        ports:
            - 8989:8989
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=sonarr.logan.loc
            - VIRTUAL_PORT=8989
        restart: always

    nzbhydra:
        image: linuxserver/hydra
        container_name: nzbhydra
        volumes:
            - /home/mike/nas_mount/config/nzbhydra:/config
            - /home/mike/nas_mount/Downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 5075:5075
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbhydra.logan.loc
            - VIRTUAL_PORT=5075
        restart: always

    muximux:
        image: linuxserver/muximux
        container_name: muximux
        volumes:
            - /home/mike/nas_mount/config/muximux:/config
            - /etc/localtime:/etc/localtime:ro
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=muximux.logan.loc
        restart: always

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        volumes:
            - /home/mike/nas_mount/config/radarr:/config
            - /home/mike/nas_mount/Movies:/movies
            - /home/mike/nas_mount/Downloads/complete:/complete
            - /etc/localtime:/etc/localtime:ro
        ports:
            - 7878:7878
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=radarr.logan.loc
            - VIRTUAL_PORT=7878
        restart: always

    nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /home/mike/nas_mount/config/nzbget:/config
            - /home/mike/nas_mount/Downloads/complete:/complete
            - /home/mike/nas_mount/Downloads:/downloads
        ports:
            - 6789:6789
        env_file: uidgid.env
        environment:
            - VIRTUAL_HOST=nzbget.logan.loc
            - VIRTUAL_PORT=6789
        restart: always

    emby:
        image: emby/embyserver
        container_name: emby
        network_mode: host
        ports:
            - 8096:8096
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /home/mike/nas_mount/config/emby:/config
            - /home/mike/nas_mount:/media:ro
        environment:
            - VIRTUAL_PORT=8096
            - VIRTUAL_HOST=emby.logan.loc
            - AUTO_UPDATES_ON=true
            - UID=1024
            - GID=100